
import { Metadata } from "next";
import React from 'react';
import SignIn from "./auth/signin/page";
import { Provider } from 'react-redux';
import { PersistGate } from 'redux-persist/integration/react';
import store, { persistor } from '../redux/store';

export const metadata: Metadata = {
  title: "TripNest Admin",
  description: "Generated by TripNest Limited",
};

export default function Home() {
  return (
    <>
    {/* <Provider store={store}>
     <PersistGate loading={null} persistor={persistor}> */}
         <SignIn/>
     {/* </PersistGate>
   </Provider> */}
      {/* <SignIn>            
      </SignIn> */}
      {/* <h2>Hello</h2> */}
    </>
  //   <Provider store={store}>
  //   <PersistGate loading={null} persistor={persistor}>
  //       <SignIn>            
  //      </SignIn>
  //   </PersistGate>
  // </Provider>
  );
}
